### ISSUE TITLE
Add LICENSE file in repo.

### ISSUE THREAD

**Issue by Rupeshiya** [collective/plonetheme.booster#10]
Instead of having LICENSE in readme.md only ,should also be there in repo file.
@tkimnguyen what do you think ??

**Comment by tkimnguyen** [comment]
Thanks @Rupeshiya  - done! 
https://github.com/collective/plonetheme.booster/commit/dcf1a18e34e83b05816dc4906c822de34b8d2a6 5

**Comment by tkimnguyen** [comment]
and 
https://github.com/collective/plonetheme.future_imperfect/commit/c5831ea1b141af7a2b0988de07f25531a6225fda

**Comment by Rupeshiya** [comment]
Good to go awesome .@tkimnguyen .
