### ISSUE TITLE
I/O warning : failed to load external entity "/slider-images/@@slider-images"

### ISSUE THREAD

**Issue by petersta** [collective/plonetheme.booster#2]
In rules.xml this reference causes error on the home page when dynamic slider is not installed.

  
  <replace
    if="$is_zip"
    css:theme="#carousel-example-generic"
    css:content="#carousel-example-generic"
    href="/slider-images/@@slider-images"
    />

**Comment by vikas-parashar** [comment]
Yeah, That's why it is advised in [user doc's](https://github.com/vikas-parashar/plonetheme.booster/blob/master/docs/index.rst) to create a slider-images folder first and put the images for the slider, then activate the theme. If User doesn't want the dynamic slider he can install the theme as zip.
