### ISSUE TITLE
Error activating theme in Plone 5.0.6 

### ISSUE THREAD

**Issue by rafaeltcc** [collective/plonetheme.booster#4]
UPDATE: Installing from zip file all went ok!

In a fresh Plone 5.0.6 install I activate the theme installed by buildout and I get the following error message:

    Tag section invalid [49:32]
    Tag header invalid [53:43]
    Tag nav invalid [57:57]
    ID portal-searchbox already defined [70:38]
    Tag aside invalid [93:41]
    Tag main invalid [96:78]
    Tag footer invalid [109:39]

<rules xml:id="r0">

  <theme href="index.html" xml:id="r1"/>
  <notheme if="$ajax_load" xml:id="r2"/>

  
  <before css:theme-children="body" css:content-children="#edit-bar" css:if-not-content=".ajax_load" css:if-content=".userrole-authenticated" xml:id="r3"/>
  <replace css:theme="#anonymous-actions" css:content-children="#portal-personaltools-wrapper" css:if-not-content=".ajax_load" css:if-content=".userrole-anonymous" xml:id="r4"/>
  <drop attributes="class" css:content="#edit-bar a.pat-plone-modal" xml:id="r5"/>

  <notheme css:if-not-content="#visual-portal-wrapper" xml:id="r6"/>

  <rules css:if-content="#portal-top" xml:id="r7">
    
    <copy attributes="*" css:theme="html" css:content="html" xml:id="r8"/>
    
    <before css:theme="head title" css:content="head base" xml:id="r9"/>
    
    <replace css:theme="head title" css:content="head title" xml:id="r10"/>
    
    <after css:theme-children="head" css:content="head meta" xml:id="r11"/>
    
    <drop css:content="head link[rel='apple-touch-icon'], head link[rel='shortcut icon']" xml:id="r12"/>
    
    <after css:theme-children="head" css:content="head link" xml:id="r13"/>
    <after css:theme-children="head" css:content="head style" xml:id="r14"/>
    
    <after css:theme-children="head" css:content="head script" xml:id="r15"/>
  </rules>

  
  <copy attributes="*" css:content="body" css:theme="body" xml:id="r16"/>

  
  <replace css:theme=".navbar-brand" css:content="#portal-logo" xml:id="r17"/>

  
  <replace css:content-children="#portal-globalnav" css:theme-children="#navbar" xml:id="r18"/>

  <replace css:theme-children=".navbar-nav" css:content-children=".plone-navbar-nav" xml:id="r19"/>

  <xsl:template match="//ul//@class[contains(., 'selected')]">
    <xsl:attribute name="class"><xsl:value-of select="."/> active</xsl:attribute>
  </xsl:template>

  
  <replace if="$is_zip" css:theme="#carousel-example-generic" css:content="#carousel-example-generic" href="/slider-images/@@slider-images" xml:id="r20"/>

  
  <replace css:theme="#site-banner" if-not="$is_zip" xml:id="r21">
    <div id="site-banner-img">
      <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="fh5co-owl-text-wrap item">
                    <div class="fh5co-owl-text site-heading text-center to-animate">
                        <h1 class="fh5co-lead">
                          <xsl:value-of select="$site_title"/>
                        </h1>
                        <h2 class="fh5co-sub-lead">
                          <xsl:value-of select="$slogan"/>
                        </h2>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </replace>

  
  <drop css:theme="#carousel-example-generic" css:if-not-content=".section-front-page" xml:id="r22"/>
  <drop css:theme="#carousel-example-generic" css:if-content=".template-edit" xml:id="r23"/>
  <drop css:theme="#carousel-example-generic" css:if-content=".template-topbar-manage-portlets" xml:id="r24"/>

  <drop css:theme="#site-banner" css:if-not-content=".section-front-page" xml:id="r25"/>
  <drop css:theme="#site-banner" css:if-content=".template-edit" xml:id="r26"/>
  <drop css:theme="#site-banner" css:if-content=".template-topbar-manage-portlets" xml:id="r27"/>

  
  <replace css:content="#portal-searchbox" css:theme="#portal-searchbox" xml:id="r28"/>

  <replace css:content="div#portal-searchbox input.searchButton" xml:id="r29">
    <button class="search-icon" type="submit">
      <i class="icon-search"/>
    </button>
  </replace>

  <replace css:content="div.mobile-live-search #portal-searchbox input.searchButton" xml:id="r30">
    <button class="search-icon">
      <i class="icon-search"/>
    </button>
  </replace>

  
  <after css:theme-children=".navbar-nav" css:content="#portal-anontools" css:if-not-content=".ajax_load" css:if-content=".userrole-anonymous" xml:id="r31"/>

  <rules css:if-content="#portal-anontools" xml:id="r32">
    <strip css:content="div#portal-anontools ul" xml:id="r33"/>
    <strip css:content="#portal-anontools" xml:id="r34"/>
  </rules>

  
  <replace css:theme-children="#above-content" css:content-children="#viewlet-above-content" xml:id="r35"/>

  
  <replace css:theme-children="#global_statusmessage" css:content-children="#global_statusmessage" xml:id="r36"/>

  
  <replace css:theme="#content-container" method="raw" xml:id="r37">
    <xsl:variable name="central">
      <xsl:if test="//aside[@id='portal-column-one'] and //aside[@id='portal-column-two']">col-xs-12 col-sm-6</xsl:if>
      <xsl:if test="//aside[@id='portal-column-two'] and not(//aside[@id='portal-column-one'])">col-xs-12 col-sm-9</xsl:if>
      <xsl:if test="//aside[@id='portal-column-one'] and not(//aside[@id='portal-column-two'])">col-xs-12 col-sm-9</xsl:if>
      <xsl:if test="not(//aside[@id='portal-column-one']) and not(//aside[@id='portal-column-two'])">col-xs-12 col-sm-12</xsl:if>
    </xsl:variable>

    <div class="{$central}">
      <div class="row">
        <div class="box">
          <div class="col-xs-12 col-sm-12">
            <xsl:apply-templates css:select="#content"/>
          </div>
          <div class="clearFix"/>
        </div>
      </div>
      <section id="viewlet-below-content-body" class="row">
        <div class="box">
          <div class="col-xs-12 col-sm-12">
            <xsl:copy-of css:select="#viewlet-below-content"/>
          </div>
          <div class="clearFix"/>
        </div>
      </section>
    </div>
  </replace>

  
  <rules css:if-content="#portal-column-one" xml:id="r38">
    <replace css:theme="#column1-container" xml:id="r39">
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas">
        <aside id="portal-column-one">
          <xsl:copy-of css:select="#portal-column-one > *"/>
        </aside>
      </div>
    </replace>
  </rules>

  
  <rules css:if-content="#portal-column-two" xml:id="r40">
    <replace css:theme="#column2-container" xml:id="r41">
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="complementary">
        <aside id="portal-column-two">
          <xsl:copy-of css:select="#portal-column-two > *"/>
        </aside>
      </div>
    </replace>
  </rules>

  
  <replace css:theme-children="#portal-footer-wrapper" css:content-children="#portal-footer-wrapper" xml:id="r42"/>

  
  <xsl:template match="//div//@class[contains(., 'fieldErrorBox')]">
    <xsl:attribute name="class">
      <xsl:value-of select="."/> alert-danger
    </xsl:attribute>
  </xsl:template>

</rules>

**Comment by vikas-parashar** [comment]
Please read the [documentation for the addon version](https://github.com/collective/plonetheme.booster/blob/master/docs/index.rst). You need to create a folder before activating thee theme.
